services:
  core:
    image: ghcr.io/loferreira/fiapsub2-core:sha-5643dac
    container_name: fiapsub2-core
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/fiapsub2-firebase-sdk.json
    volumes:
      - type: bind
        source: ./fiapsub2-firebase-sdk.json
        target: /app/fiapsub2-firebase-sdk.json
        read_only: true
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api-docs.json",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on:
      - core
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - CORE_API_BASE_URL=http://core:3000
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-fiapsub2-sales}
    volumes: []
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api-docs.json",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  app-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - core
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - CORE_API_BASE_URL=http://core:3000
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-fiapsub2-sales}
    volumes:
      - ./src:/app/src:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./.env:/app/.env:ro
    command: npm run start
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
