apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapsub2-sales-deployment
  labels:
    app: fiapsub2-sales
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiapsub2-sales
  template:
    metadata:
      labels:
        app: fiapsub2-sales
    spec:
      containers:
        - name: fiapsub2-sales
          image: fiapsub2-sales:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: fiapsub2-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: fiapsub2-config
                  key: PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: fiapsub2-config
                  key: HOST
            - name: CORE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: fiapsub2-config
                  key: CORE_API_BASE_URL
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_URI
            - name: MONGODB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fiapsub2-config
                  key: MONGODB_DB_NAME
          volumeMounts: []
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health/db
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/db
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
